apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-redis-app
  labels:
    app: flask-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-front
  template:
    metadata:
      labels:
        app: flask-front
    spec:
      containers:
      - name: flask-front-end
        image: iampawar/front-app
        ports:
        - containerPort: 5000  
