apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-redis-app
  labels:
    app: flask-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-front
  template:
    metadata:
      labels:
        app: flask-front
    spec:
      containers:
      - name: flask-back-end
        image: docker.io/redis
        imagePullPolicy: IfNotPresent

      - name: flask-front-end
        image: docker.io/iampawar/flask
        imagePullPolicy: IfNotPresent

